name       : quazip
version    : 0.7.3
release    : 3
source     :
    - http://pilotfiber.dl.sourceforge.net/project/quazip/quazip/0.7.3/quazip-0.7.3.tar.gz : 2ad4f354746e8260d46036cde1496c223ec79765041ea28eb920ced015e269b5
license    : LGPL-2.1
summary    : Wrapper to access ZIP archives using Qt
component  : desktop.qt
description: |
    QuaZIP is a simple C++ wrapper that can be used to access ZIP archives using the Qt toolkit.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
