name       : quazip
version    : 0.7.6
release    : 4
source     :
    - https://github.com/stachenov/quazip/archive/0.7.6.tar.gz : 4118a830a375a81211956611cc34b1b5b4ddc108c126287b91b40c2493046b70
license    : LGPL-2.1-or-later
summary    : Qt/C++ wrapper over minizip
component  : desktop.qt
description: |
    QuaZIP is a simple C++ wrapper that can be used to access ZIP archives using the Qt toolkit.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %patch -p1 < $pkgfiles/quazip-0.7.6-fix_static.patch

    %cmake . -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %make
install    : |
    %make_install
