name       : quazip
version    : 0.7.2
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/quazip/quazip/0.7.2/quazip-0.7.2.tar.gz : 91d827fbcafd099ae814cc18a8dd3bb709da6b8a27c918ee1c6c03b3f29440f4
license    : LGPL-2.1
summary    : Wrapper to access ZIP archives using Qt
component  : desktop.qt
description: |
    QuaZIP is a simple C++ wrapper that can be used to access ZIP archives using the Qt toolkit.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check