name       : quazip
version    : 0.9.1
release    : 6
source     :
    - https://github.com/stachenov/quazip/archive/refs/tags/v0.9.1.tar.gz : 5d36b745cb94da440432690050e6db45b99b477cfe9bc3b82fd1a9d36fff95f5
license    : LGPL-2.1-or-later
summary    : Qt/C++ wrapper over minizip
component  : desktop.qt
description: |
    QuaZIP is a simple C++ wrapper that can be used to access ZIP archives using the Qt toolkit.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/libquazip5.a
